backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts -> this creates branches & pull requests
publish_mode: editorial_workflow

media_folder: "static/media" # Media files will be stored in the repo under images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: rumyra
    api_key: 871382599576712
    folder:
      - path: portfolio

logo_url: "static/images/logo.svg"

collections:

  # Publications -> articles, papers, books, tech writing
  - name: "writing"
    identifier_field: "name" # this is the part of the data for the unique title (defaults to title)
    label: "Writings"
    label_singular: "Writing"
    description: "Any articles, publications, books(!), tech writing etc..."
    folder: "writings"
    create: true
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      # default
      # required
      # pattern
      - { label: "Release Date", name: "releaseDate", widget: "datetime", format: "Do MMM, YYYY" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Link", name: "website", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # Publications -> articles, papers, books, tech writing
  - name: "projects"
    identifier_field: "title" # this is the part of the data for the unique title (defaults to title)
    label: "Projects"
    label_singular: "Project"
    description: "All work projects, demos, personal art projects, community builds"
    folder: "projects"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      # default
      # required
      # pattern
      - { label: "Collection", name: "collection", widget: "select", options: ["Work", "Demo", "Personal", "Community", "Art"]}
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: true }

      - {label: "Link", name: "url", widget: "string"}
      - {label: "Github", name: "github", widget: "string", required: false }

      - { label: "Client (name)", name: "client", widget: "string", required: false }
      - { label: "Client URL", name: "client_url", widget: "string", required: false }

      - {label: "Location", name: "location", widget: "map", required: false }

      - { label: "Date From", name: "date_from", widget: "datetime", format: "Do MMM, YYYY" }
      - { label: "Date To", name: "date_to", widget: "datetime", format: "Do MMM, YYYY", required: false}

      - label: "Media"
        name: "media"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
            folder:
              - path: portfolio
      - { label: "Layout", name: "layout", widget: "select", options: ["Work", "Demo", "Personal", "Community", "Art"]}
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - { label: "Multi Image", value: "0" }
          - { label: "Video", value: "1" }
          - { label: "Single Image", value: "2" }

      - label: "Quote"
        name: "quote"
        widget: "object"
        required: false
        fields:
          - {label: "Quote Text", name: "q", widget: "string", required: false}
          - {label: "Cite", name: "cite", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}

      - label: "Tech Used"
        name: "tech"
        widget: "list"
        default: ["express", "nodejs", "heroku", "SCSS", "pug"]

      - { label: "Body", name: "body", widget: "markdown", required: false }

  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Body", name: "body", widget: "markdown" }
